image:
  - macOS
  - Ubuntu
  - Visual Studio 2017

stack: node 8, jdk 8
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  nodejs_version: "8"
  GRADLE_OPTS: -Dorg.gradle.daemon=false

before_test:
  - sh: curl -s "https://get.sdkman.io" | bash
  - sh: source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sh: sdk install java `sdk list java | grep "8.[0-9]*.[0-9]*-zulu" | head -1 | awk '{print $NF}'` && java -version
  - sh: export JAVA_HOME=$HOME/.sdkman/candidates/java/current

test_script:
  - sh: ./gradlew clean test
  - cmd: gradlew.bat clean test

# Don't actually build.
build: off
